config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    collection do
      get :filter
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save!

    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  def filter
    @flats = Flat.where('name like ?', params[:search])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :lat, :long)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div class="card">
  <img src="https://source.unsplash.com/1600x900/" class="card-img-top" alt="<%= flat.name %>">
  <div class="card-body flex-container flex-column justify-content-between">
    <div>
        <h5 class="card-title font-weight-bold"><%= flat.name %> apartment</h5>
        <p class="card-text "><%= flat.description %></p>
    </div>
    <div>
        <%= link_to 'View', flat, class: 'btn btn-info btn-block align-bottom'  %>
    </div>
  </div>
</div>

app/views/flats/_form.html.erb
  <%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.input :lat %>
  <%= f.input :long %>
  <%= f.submit %>
  <% end %>

app/views/flats/edit.html.erb
<div class = "container mt-5">
  <div class = "mb-4">
    <h1>Edit <%= @flat.name%></h1>
  </div>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/filter.html.erb
<div class ="container mt-4">
  <div class ="m-2">
    <h1>Filtered flats</h1>
  </div>
  <div class ="cards">
    <%= render @flats %>
  </div>

</div>

app/views/flats/index.html.erb
<div class ="container mt-4">
  <div class ="m-2">
    <h1>All our flats </h1>
  </div>
  <div class ="cards">
    <%= render @flats %>
  </div>

</div>

app/views/flats/new.html.erb
<div class = "container mt-5">
  <div class = "mb-4">
    <h1>Add in a new Flat</h1>
  </div>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class = "container mt-5">
  <h1><strong><%= @flat.name%> apartment</strong>
    <large>
        <%= link_to edit_flat_path do %>
            <i class="fas fa-pencil-alt"></i>
        <% end %>
        <%= link_to flat_path(@flat), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash-alt"></i>
        <% end %>
    </large>
  </h1>
  <br>
  <div class = "card p-5">
  <img src="../../assets/Desktop.PNG" class="card-img-top" alt="Map">
  </div>
  <br>

  <div class="card">
    <div class="card-header">
      <h4> <strong>Location</strong> </h4>
    </div>
    <div class="card-body">
        <h5 class="card-title"><%= @flat.address %></h5>
    </div>
  </div>
  <br>

    <div class="card">
    <div class="card-body">
        <h5 class="card-title font-weight-bold">A bit more about this apartment</h5>
        <p class="card-text"><%=@flat.description %></p>

    </div>
  </div>
  <br>

    <div class="card">
    <div class="card-body">
        <h5 class="card-title font-weight-bold">Details</h5>
        <p class="card-text">Guests: <%=@flat.number_of_guests%></p>
        <p class="card-text">Price per night: $<%=@flat.price_per_night%></p>
    </div>
  </div>
</div>